### ISSUE TITLE
Please put marker-icon-2x.png for retina displays

### ISSUE THREAD

**Issue by somenxavier** [perrygeo/leaflet-simple-csv#10]
Hi,

`marker-icon-2x.png` which simply doubles the original icon is "needed" by retina displays. You can get it from my [commit](https://github.com/somenxavier/powered-by-somenergia/commit/b2f3d915f12bacff9e66b8caca0a2818ec1ea31e) resolving this issue in my maps..

**Comment by perrygeo** [comment]
Styling of the map is custom for each user so if anyone wants to use 2x retina markers, they are free to do so. It doesn't really fall under the scope of this project though.

**Comment by somenxavier** [comment]
OK. Good to know.
