### ISSUE TITLE
Problem reading cvs file

### ISSUE THREAD

**Issue by matteomanca** [perrygeo/leaflet-simple-csv#12]
Hi all,
I'm facing some problem reading the cvs file; I rename the config.s.template in config.js and I'm testing with the data.cv file included in the original project but I got the following error:

"Error retrieving csv file" that seems to depend on a "requested page not found [404]" error.

Do you have any idea that could help me to figure out what I'm missing?
Thanks in advance.

**Comment by perrygeo** [comment]
@matteomanca - what does the `dataUrl` in your config look like?

The file must be located at that exact path *relative to the base directory*. IOW if my config.js says

    var dataUrl = 'data/data.csv';

I should be able to run from the base directory:

    $ ls data/data.csv

If not, change your config or change your file's location accordingly.

**Comment by matteomanca** [comment]
Thank you for your reply @perrygeo. This is the dataUrl in the config.js file:
`var dataUrl = 'data/data.csv';`
and the `data.cv` file is located in the data directory, so I' m able to see the file from my base directory. I also tried to set the absolute path (just as proof) but it doesn't solve the problem.

**Comment by perrygeo** [comment]
You mean `data.csv` with an **s**?

**Comment by matteomanca** [comment]
Yes sure, data.csv. That's just a typo.

**Comment by perrygeo** [comment]
You'll need to provide more info about your setup then because I can confirm that this works out of the box:

```
git clone https://github.com/perrygeo/leaflet-simple-csv.git
cd leaflet-simple-csv
cp config.js.template config.js
open index.html
```
If you're doing something different and it's causing errors, please provide the details so we can figure it out.

**Comment by matteomanca** [comment]
ok it works. I do not know what I was missing.
Anyway, thanks a lot for your help!!

**Comment by perrygeo** [comment]
@matteomanca No problem - I'll add that bit of code to the README to make it more clear. Thanks for working through it with me!
