### ISSUE TITLE
CSV file does't works out of the box

### ISSUE THREAD

**Issue by dasistglitch** [perrygeo/leaflet-simple-csv#15]
Hello. I tried:
— download zip-file from "leaflet-simple-csv";
— clone according to the readme instructions;
— clone and download zip;
But whatever i have 'Error retrieving csv file'.

The template on my github [https://github.com/dasistglitch/map](url)

**Comment by perrygeo** [comment]
I'm afraid that's not enough information to help you. I can confirm that the steps in the README work. Can you paste the *exact* steps that you took, noting how they differ from theinstructions in *any* way.

**Comment by dasistglitch** [comment]
1. Created a new repository on github.com
2. Imported code https://github.com/perrygeo/leaflet-simple-csv.git
3. Opened Git bash on PC
4. `git clone https://github.com/perrygeo/leaflet-simple-csv.git`
5. `cd leaflet-simple-csv`
6. `git mv config.js.template config.js`
7. `start index.html`
8. Got message "Error retrieving csv file". Map is open.

data.csv in 'data' folder.

**Comment by perrygeo** [comment]
I'm not familiar with the `start` command. Just to remove any variables, try opening the index.html file directly in a browser using the file:// protocol to test it.

**Comment by dasistglitch** [comment]
`start` command opens standard browser. I tried open the index.html at browser "Drag-and-drop" and "right mouse". csv-file doesn't open.

**Comment by perrygeo** [comment]
> csv-file doesn't open

Can you provide more info. What URL is the console trying to open? Is it a `file://` protocol URI or other?

**Comment by dasistglitch** [comment]
file:///C:/map2/index.html 

Maybe problem with leaflet or jquery scripts?

**Comment by perrygeo** [comment]
The javascript makes an xmlhttprequest to get the csv file. Some browsers may not accept such requests for the `file://` protocol. Check your javascript console to see if that's the case.

If so you'll need to serve the file by another protocol, presumably `http://` via a web server of some sort.

For example, you can use Python to start a simple web server from that directory
```
leaflet-simple-csv$ python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
```
Then navigate to `http://localhost:8000` instead.

**Comment by perrygeo** [comment]
@dasistglitch I just confirmed the behavior on Google Chrome. I'll add a note to the README.

**Comment by dasistglitch** [comment]
Interesting... 
Opera, Chrome and IE — error.
FireFox — working.

Only Python and web server can fix this problem?

**Comment by ckhung** [comment]
Does this help? Start chrome from the command line: `chromium-browser --allow-file-access-from-files` and try again.

**Comment by perrygeo** [comment]
@dasistglitch That's just how browsers implement security on different protocols. If you want ajax on a file:// protocol, use a browser that support it or configure your browser to support it. Otherwise use a web server that speaks http://. It's the same situation with *any* javascript application that uses AJAX requests, nothing unique about this project in that regard.

**Comment by dasistglitch** [comment]
Thx for help!
