### ISSUE TITLE
Custom icons and popup text disappearing?

### ISSUE THREAD

**Issue by megalithicportal** [perrygeo/leaflet-simple-csv#7]
Hello Matthew, I've created a map for my site based on the script - it is so nearly there but there's a strange problem with custom icons and popups. Here's the demo:
http://www.megalithic.co.uk/leaflet_megalith_map.php?country=3

If I search for something in the text search box - below the 'Scotland' drop down. (try Well)

But click on Search. Then all the map icons disappear and when you click on a popup it says 'undefined'

But then click on Search again and the icons come back and also the popups come back!

I can't work it out... :(
Many thanks for a fab script and if you can help with this silly problem.

How it works: 
The app code with the added customisation is here
www.megalithic.co.uk/leaflet/app.js

My CSV file with icons is here 
http://www.megalithic.co.uk/cache/csvmap_country3.csv

There's a column called Icon which contains the name of the custom icon - eg tr2 creates a link to the icon wanted for that row, eg
http://www.megalithic.co.uk/images/mapic/tr2.gif
etc...

There's also a column called Thumb which has a thumbnail image for that pop-up - this all works fine.

You're welcome to add the custom icons / thumbnail idea to your base code if you like
Thanks
Andy
http://www.megalithic.co.uk
Non profit ancient sites web resource

**Comment by perrygeo** [comment]
Looks great, I took a quick look at your custom code and this line:

                iconUrl: 'images/mapic/'+feature.properties.icon+'.gif',

Seems to be the issue. You should probably check for feature.properties.icon and put a debug trace in to handle when it is undefined.

**Comment by megalithicportal** [comment]
Thanks, the whole feature.properties structure seems to disappear as all the popup information becomes undefined as well. I'm not a javascript coder, I'm just feeling my way by luck. I can't see a private message option on here. I appreciate you're not a freelancer and no offence intended but would you consider debugging it in return for some beer money or other thank you of some sort? andy@megalithic.co.uk

**Comment by megalithicportal** [comment]
Hello - my friend Jan fixed the problem with the disappearing site icons and other data
He commented out this line in "leaflet.geocsv.js":

if (prop == '' || prop == '_' || this._propertiesNames.indexOf(prop) >= 
0) prop = 'prop-' + i;
