### ISSUE TITLE
Can you provide documentation about the config?

### ISSUE THREAD

**Issue by somenxavier** [perrygeo/leaflet-simple-csv#8]
Hi,

I think some items are self-explanatory, but some not. For example, `var subdomains`. Can you provide some documentation (Javascript comments are enough) for that?

Thanks in advance,

**Comment by perrygeo** [comment]
the `subdomains` variable is used by leaflet to request tiles from different URLS as described in the "URL Template" section at http://leafletjs.com/reference.html#tilelayer

`clusterOptions` is passed directly as the first argument to leaflet's `L.MarkerClusterGroup` constructor.

The rest are fairly self-explanatory; contact me or start a new issue if there is any further confusion.

**Comment by somenxavier** [comment]
Is the documentation updated? Thanks

**Comment by perrygeo** [comment]
There is no official documentation for the config file yet. I feel that the options are simple enough to stand on their own and any attempt to document them would be basically reiterating the leaflets docs
