### ISSUE TITLE
[question] How can get all items with keyword

### ISSUE THREAD

**Issue by somenxavier** [perrygeo/leaflet-simple-csv#9]
Hi,

In my [repo](https://github.com/somenxavier/powered-by-somenergia/tree/inestable) I used your tool. It's awesome. I have a question: the CSV data [file](https://github.com/somenxavier/powered-by-somenergia/blob/inestable/data/data.csv) have keywords ("Paraules clau"). 

I want map to see the items with specific keyword when I press over it. How can do achieve it? What is the url I have to use to request all items with keyword 'X'?

**Comment by perrygeo** [comment]
In your config file, set
    var labelColumn = "Paraules clau";

**Comment by somenxavier** [comment]
But `What is the url I have to use to request all items with keyword 'X'?`?

**Comment by perrygeo** [comment]
There is no mechanism to do this by URL parameters. I'd accept a pull request if you care to attempt it.

**Comment by somenxavier** [comment]
No. I have no tech skills. Mark it as wish.
